### ISSUE TITLE
'replace_with_body_fragments' method has bug ?

### ISSUE THREAD

**Issue by creeek** [mwelham/office_docs#3]
lib/office/word.rb L579~590 #replace_with_body_fragments 

``` ruby
@paragraph.node.next_sibling.xpath(".//w:p").each do |p_node|
  p = Paragraph.new(node, @paragraph.document)
  @paragraph.document.paragraph_inserted_after(@paragraph, p)
end
```

p = Paragraph.new(node, @paragraph.document)
==>   p = Paragraph.new(p_node, @paragraph.document)

**Comment by mwelham** [comment]
Thanks for spotting that.

It's been fixed.
